FROM golang:1.14.4 AS build
RUN git clone https://github.com/envoyproxy/ratelimit /ratelimit
WORKDIR /ratelimit

ENV GOPROXY=https://proxy.golang.org
RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -v -o ./bin/ratelimit ./src/service_cmd/main.go

FROM alpine:3.11 AS final
RUN apk --no-cache add ca-certificates
COPY --from=build /ratelimit/bin/ratelimit /bin/ratelimit
COPY ./ratelimit-config/config.yaml /data/ratelimit/config.yaml
ENTRYPOINT ["./bin/ratelimit"]