version: '3.7'
services:
  redis:
    image: redis:6.0.5-alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      ratelimit:
        aliases:
          - redis

  ratelimitsvc:
    build:
      context: .
      dockerfile: Dockerfile-ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      ratelimit:
        aliases: 
          - ratelimitsvc
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      # This means we will put the data in /data/ratelimit.
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
  
  envoy:
    image: envoyproxy/envoy:v1.15.0
    command: /usr/local/bin/envoy -c /config/envoy-ratelimit.yaml -l debug
    networks:
      ratelimit:
    volumes:
     - "./envoy-ratelimit.yaml:/config/envoy-ratelimit.yaml"
    ports:
     - "9080:9080"
     - "8001:8001"
  
  httpserver:
    build:
      context: .
      dockerfile: Dockerfile-httpserver
    ports:
      - "9000:9000"
    networks:
      ratelimit:
        aliases:
          - httpserver
    depends_on:
     - envoy

networks:
  ratelimit: